### ISSUE TITLE
README-related questions

### ISSUE THREAD

**Issue by LappleApple** [zalando/camunda-cockpit-client#11]
Hey, I have a few questions:
-- Line 20: which script are you referring to?

And based from this: https://github.com/zalando/zalando-howto-open-source/blob/master/producttemplate.md:
-- What is your vision for this project?
-- Do you need/want the open-source community to help you with this project?
-- What are the main “why you should use this” message points? (this is the only tool out there achieving its objectives, for example)
-- Who are the primary target users, besides Camunda users? Camunda users in what contexts/trying to do what things?

Also, from here https://github.com/zalando/zalando-howto-open-source/blob/master/producttemplate.md:
-- State if it is out-of-the-box user-friendly, so it’s clear to the user.
-- Note its development status.
-- Include badges/code coverage, build report, whatever makes sense to you
-- make sure these are clear: Getting Started/Requirements/Prerequisites/Dependencies
-- Contributor guidelines and if there are to-do's

**Comment by jhorstmann** [comment]
> What is your vision for this project?

I don't understand the need for a "vision". The tool solves a problem we have and so is already very useful.

> Do you need/want the open-source community to help

Yes, there are [some open issues](https://github.com/zalando/camunda-cockpit-client/issues) with `help wanted` or `enhancement` labels.

> What are the main “why you should use this” message points

As the README says: "Retrying multiple incidents using the Cockpit web app is very cumbersome."

> Who are the primary target users, besides Camunda users

Since we use the camunda rest api, the tool is only useful for camunda users. The context would be doing bulk operations for multiple incidents, since individual incidents could already be solved using the camunda cockpit webapp.

**Comment by meyerdan** [comment]
Hi @jhorstmann,

just FYI: with the upcoming 7.6.0 release, we introduce the batch operation APIs (Java / REST) and UI features in cockpit which may be interesting for this tool:

* http://stage.docs.camunda.org/manual/develop/reference/rest/job/post-set-job-retries/
* http://stage.docs.camunda.org/manual/develop/webapps/cockpit/batch/batch-operation/

With these features you can increment retires for all jobs matching a given query and so on ...

**Comment by LappleApple** [comment]
Hi @meyerdan: if you can elaborate, we can include the relevant details in this repo's README.

**Comment by meyerdan** [comment]
Not sure whether it should be mentioned in the README. Just wanted to let you know that there is new APIs available which are within the usecase scope of what @jhorstmann mentioned above: 

> The context would be doing bulk operations for multiple incidents, since individual incidents could already be solved using the camunda cockpit webapp.

It could be interesting to expose these new APIs to users of this tool.

**Comment by jhorstmann** [comment]
Once 7.6 is released and our services are updated we will probably change this tool to use the new apis. One feature this tool has which can't be easily replicated in a cockpit plugin is to execute the same query and update on multiple (sharded) process engines.

**Comment by LappleApple** [comment]
@meyerdan Thank you. I'm wondering if you have any thoughts on how promote-able this repo might be; doesn't seem to be getting traction, but perhaps we're not connecting to the right audience. Do you have any thoughts?

**Comment by LappleApple** [comment]
@meyerdan Hello again -- wondering if you could help @jhorstmann promote this repo a bit to your audience so that it can gain more exposure. Are you open to that?

**Comment by meyerdan** [comment]
Hi, sorry for not getting back sooner: there is a couple of things we can do:

- we can list it in camunda documentation both [here][1] (bottom of the page) and [here][2] to give it more visibility.
- You could release the project and publish a blogpost on blog.camunda.org (can also be a post on the zalando tech blog with a smaller post liking to it on the camunda community blog)
- When there is a release with a blogpost, we can tweet about it and so on
- I think that this kind of CLI project is best demonstrated with a short, very to the point, video. That can be embedded in the project's README, on a blog and also on twitter
- @jhorstmann  can demonstrate the project at Camunda community events. 
- It is also possible to transfer the repository to the camunda GH organization to give it visibility there. (Here is an example of a repository like that: https://github.com/camunda/camunda-bpm-spring-boot-starter - that is completely maintained by the community).

What is always hard to judge is how large the need in the community is for a particular project. But the only way to find that out is to make some noise and interpret the results (GH stars, blogpost views, Video plays, twitter likes ...).

Best,
Daniel

[1]: https://docs.camunda.org/manual/latest/
[2]: https://docs.camunda.org/manual/7.6/introduction/extensions/#community-extensions

**Comment by meyerdan** [comment]
I will go ahead and list the project in the community extensions: https://app.camunda.com/jira/browse/CAM-7229

**Comment by LappleApple** [comment]
Thank you, @meyerdan. This all sounds great to me: @jhorstmann, what are your thoughts?

**Comment by meyerdan** [comment]
Examples of two meetups where this extension could be presented:
- https://www.meetup.com/camunda-vienna/
- https://www.meetup.com/Camunda-User-Group-Hamburg/

**Comment by LappleApple** [comment]
Hi @meyerdan, I haven't heard back from @jhorstmann so unless that changes I'll move this to our Incubator GitHub org until he's available to pick up this topic again.
